application: i18n-gae-python
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: i18n.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
